import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  // Static routes - prerender for best SEO and performance
  { path: '', renderMode: RenderMode.Prerender },
  { path: 'home', renderMode: RenderMode.Prerender },
  { path: 'privacy', renderMode: RenderMode.Prerender },
  { path: 'impressum', renderMode: RenderMode.Prerender },
  { path: 'projects', renderMode: RenderMode.Prerender },
  { path: 'projects/image-resizer', renderMode: RenderMode.Prerender },
  { path: 'projects/image-resizer-privacy-policy', renderMode: RenderMode.Prerender },
  { path: 'projects/file-renamer/privacy-policy', renderMode: RenderMode.Prerender },
  { path: 'projects/discret-convolution', renderMode: RenderMode.Prerender },
  { path: 'contact', renderMode: RenderMode.Prerender },
  { path: 'blog', renderMode: RenderMode.Prerender },

  // Dynamic blog routes from prerender-routes.txt - prerender for SEO
  { path: 'blog/A one-layer object position estimator using the expected value', renderMode: RenderMode.Prerender },
  { path: 'blog/Dotnet docker experiences', renderMode: RenderMode.Prerender },
  { path: 'blog/Hands on - Azure Scale Sets', renderMode: RenderMode.Prerender },
  { path: 'blog/Install linux from hdd - without usb', renderMode: RenderMode.Prerender },
  { path: 'blog/Using Azure Key vault with AzureDevOps', renderMode: RenderMode.Prerender },
  { path: 'blog/Connecting to Azure Devops with a Service Principal', renderMode: RenderMode.Prerender },
  { path: 'blog/Create an Azure App registrations daemon app', renderMode: RenderMode.Prerender },
  { path: 'blog/Checkout dotnet-trace', renderMode: RenderMode.Prerender },
  { path: 'blog/Use boundary trace to find contour of object in images', renderMode: RenderMode.Prerender },
  { path: 'blog/Create a Self-Signed Certificate for Code Signing', renderMode: RenderMode.Prerender },
  { path: 'blog/Discrete Wavelet transformation', renderMode: RenderMode.Prerender },
  { path: 'blog/Discrete cosine transform', renderMode: RenderMode.Prerender },
  { path: 'blog/Signal hilbert transformation', renderMode: RenderMode.Prerender },
  { path: 'blog/Signal filtering', renderMode: RenderMode.Prerender },
  { path: 'blog/Signal sampling', renderMode: RenderMode.Prerender },
  { path: 'blog/Fast Fourier Transform', renderMode: RenderMode.Prerender },
  { path: 'blog/Working with adb aka Android Debug Bridge', renderMode: RenderMode.Prerender },
  { path: 'blog/Signal processing', renderMode: RenderMode.Prerender },
  { path: 'blog/.so undefined reference to openssl', renderMode: RenderMode.Prerender },
  { path: 'blog/ILT0005 runtime.win10-arm.microsoft.net.native.compiler tools ARM nutc_driver.exe intermediate MDIL...rsp returned exit code -1073741819', renderMode: RenderMode.Prerender },
  { path: 'blog/MDIL compilation failed', renderMode: RenderMode.Prerender },
  { path: 'blog/Add Token Authorization to AngularJS and WebApi', renderMode: RenderMode.Prerender },
  { path: 'blog/C# JsonTextReader could not read serialized json value', renderMode: RenderMode.Prerender },
  { path: 'blog/C# How to intercept and modify WCF messages via a MessageInspector', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Entity Framework ObjectContext to DbContext', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Get MD5 hash string', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Get all controls of a specific type from a visual tree', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Assign a DataContext to multiple UI controls', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Detect if Windows is running in a virtual machine', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Multithreading UI controls', renderMode: RenderMode.Prerender },
  { path: 'blog/Javascript Datejs', renderMode: RenderMode.Prerender },
  { path: 'blog/Enable SSL 3.0 and TLS 1.0, 1.1, 1.2 on Windows using PowerShell', renderMode: RenderMode.Prerender },
  { path: 'blog/Angular CLI ng build change bundle name', renderMode: RenderMode.Prerender },
  { path: 'blog/XAML DependencyProperty Binding does not work', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Get hash value of file', renderMode: RenderMode.Prerender },
  { path: 'blog/Powershell TLS settings', renderMode: RenderMode.Prerender },
  { path: 'blog/Adb windows fastboot oem cmd problem', renderMode: RenderMode.Prerender },
  { path: 'blog/Javascript change class css dynamically', renderMode: RenderMode.Prerender },
  { path: 'blog/Powershell array contains or in operator', renderMode: RenderMode.Prerender },
  { path: 'blog/Javascript check if array contains value', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Serialize and deserialize Json string', renderMode: RenderMode.Prerender },
  { path: 'blog/CSS text-overflow ellipsis on table cell td', renderMode: RenderMode.Prerender },
  { path: 'blog/Powershell create MD5 hash', renderMode: RenderMode.Prerender },
  { path: 'blog/CSS select first-, second-, third-child', renderMode: RenderMode.Prerender },
  { path: 'blog/C# .net core get application path', renderMode: RenderMode.Prerender },
  { path: 'blog/C# Read XML attributes ', renderMode: RenderMode.Prerender },
  { path: 'blog/Fixing Microsoft.AspNetCore.Server.Kestrel[0] connection id feature', renderMode: RenderMode.Prerender },

  // Category routes from prerender-routes.txt
  { path: 'category/AI', renderMode: RenderMode.Prerender },
  { path: 'category/Azure', renderMode: RenderMode.Prerender },
  { path: 'category/Dotnet', renderMode: RenderMode.Prerender },
  { path: 'category/Linux', renderMode: RenderMode.Prerender },
  { path: 'category/Signal processing', renderMode: RenderMode.Prerender },
  { path: 'category/Android', renderMode: RenderMode.Prerender },
  { path: 'category/AngularJS', renderMode: RenderMode.Prerender },
  { path: 'category/C#', renderMode: RenderMode.Prerender },
  { path: 'category/Javascript', renderMode: RenderMode.Prerender },
  { path: 'category/Angular', renderMode: RenderMode.Prerender },
  { path: 'category/XAML', renderMode: RenderMode.Prerender },
  { path: 'category/Powershell', renderMode: RenderMode.Prerender },
  { path: 'category/CSS', renderMode: RenderMode.Prerender },

  // Dynamic routes that weren't prerendered - use SSR for SEO
  { path: 'blog/:title', renderMode: RenderMode.Server },
  { path: 'category/:category', renderMode: RenderMode.Server },
  { path: 'projects/discret-convolution/h/:h/x/:x', renderMode: RenderMode.Server },

  // Catch-all route for 404s
  { path: '**', renderMode: RenderMode.Server, status: 404 }
];